### ISSUE TITLE
what are the required modules in nodemcu-firmware?

### ISSUE THREAD

**Issue by moritzmetz** [anandtamboli/1btn#1]
Hi,
I'm currently trying to run 1btn release 3 on a blank esp8266 nodemcu board and build an own 1btn for my radio show "netzbasteln". but it keeps crashing with the error " (?:0: attempt to index global 'bit' (a nil value))"
as far as i understand this can mean a lot - but maybe its because i miss some modules in the nodemcu firmware? my current modules are: file,gpio,http,net,node,tmr,uart,wifi - is there anything else i need?
thanks!
moritz

**Comment by knewron-technologies** [comment]
You also need to add 'bit' module.
