### ISSUE TITLE
Wifi Stability

### ISSUE THREAD

**Issue by ghost** [anandtamboli/1btn#2]
Our 1btn device sometimes lost the connection to the configurated wifi network.

**Comment by knewron-technologies** [comment]
Could be various reasons...
1. Battery low - insufficient power to connect
2. Router rejected connection / no ip allocated / took too long to allocate which forces 1btn back to config mode
3. Wifi network credentials have been changed

**Comment by ghost** [comment]
Ok. I'll check this.
