### ISSUE TITLE
WiFi configuration

### ISSUE THREAD

**Issue by ghost** [anandtamboli/1btn#3]
It's very difficult to configure the WiFi connection of the 1btn, because it's not possible to connect to the 1btn WiFi network by much operating systems. It doesn't work with Windows 10, Ubuntu, macOS, iOS. Only some versions of android will work.

**Comment by knewron-technologies** [comment]
We have tested with Windows, Ubuntu and Android successfully and with feedback from 300+ users, this hasn't been an issue. There has been problem with Mac and iOS though: [https://discussions.apple.com/thread/7705927?start=0&tstart=0](https://discussions.apple.com/thread/7705927?start=0&tstart=0) and it is fully dependent on settings on phone / laptop side.

**Comment by ghost** [comment]
Hey,
we've tested it with several devices. But we can't to connect with the button.

**Comment by knewron-technologies** [comment]
What errors you are seeing ?

**Comment by ghost** [comment]
For example we try to connect with a DELL Latitude E5250 (Ubuntu 16.04 LTS). We are asked for password. When we enter the password the notebook is connected to the 1btn WiFi. Several seconds later we are asked to enter the password a second time and the device can't reconnect to the 1btn.

**Comment by knewron-technologies** [comment]
A lot would depend on the client connecting to access point here. Such as what settings it has for connecting with independent APs. When you say it connects to wifi after inputting credentials first time - rest of the configuration should be after that. If configuration is not done for some time, AP will be closed and that could be the reason for asking second time.

**Comment by ghost** [comment]
I mean the connection between device and 1btn not 1btn between AP. So we can't open the 1btn configuration and can't enter the WiFi ssid and secret.

**Comment by knewron-technologies** [comment]
Yes, I am referring to the same.

With the versions you have, you can directly input creds by connecting it with USB cable and sending those details using serial-terminal software.

**Comment by aidanreilly** [comment]
Hi, Having some similar issues trying to connect and configure 1btn wifi network from the my1btn wifi hotspot. 

I can connect with the default password, but cannot browse to http://192.168.1.1 on any device - android, ios, windows. I get a red blink every time. 

I guess I'll start here and see if I can configure over serial: https://github.com/knewron-technologies/1btn/blob/master/firmware/hacking%20pre-requisites.txt

**Comment by rwatkins-BY** [comment]
Can anyone provide some information on how to configure a 1btn unit over my1btn network.  I have followed these instructions : https://onedrive.live.com/embed?cid=1CCB31E5C4946157&resid=1CCB31E5C4946157!64753&authkey=ABqqwSvGLUfaemQ&em=2
and it allows me to put in the password but when I go to a browser and put in 192.168.1.1, it never connects but it does turn on a red light briefly on the 1btn unit.   I am trying to use my android phone to make the connection at this point.

**Comment by knewron-technologies** [comment]
Try with direct hardware connection. Check above content for more info. 

> Hi, Having some similar issues trying to connect and configure 1btn wifi network from the my1btn wifi hotspot.
> 
> I can connect with the default password, but cannot browse to http://192.168.1.1 on any device - android, ios, windows. I get a red blink every time.
> 
> I guess I'll start here and see if I can configure over serial: https://github.com/knewron-technologies/1btn/blob/master/firmware/hacking%20pre-requisites.txt



> Can anyone provide some information on how to configure a 1btn unit over my1btn network. I have followed these instructions : https://onedrive.live.com/embed?cid=1CCB31E5C4946157&resid=1CCB31E5C4946157!64753&authkey=ABqqwSvGLUfaemQ&em=2
> and it allows me to put in the password but when I go to a browser and put in 192.168.1.1, it never connects but it does turn on a red light briefly on the 1btn unit. I am trying to use my android phone to make the connection at this point.
