### ISSUE TITLE
API security issues

### ISSUE THREAD

**Issue by ghost** [anandtamboli/1btn#4]
It's possible to trigger the 1btn api without the 1btn.

I need only the mac address of a 1btn and can execute api requests. Because the mac address and the http agent header are the only information which are checked. I think this is a security problem, because the mac address isn't a private information. This address is at layer one of the osi model. So it's visible for all network members.

A second problem is that your api isn't secure with ssl.

**Comment by knewron-technologies** [comment]
Apart from **mac address** (which is not private), one will also need **username** and **password** along with api-key code, which are private to 1btn users. If that is not shared / exposed by users, API can't be accessed.

For open source product users, it doesn't have SSL. However, for 1btn-pro users we provide SSL as well as other security options where data can't be spoofed.

**Comment by ghost** [comment]
Hi,
i mean the connection between button and your api. If you like i can provide you a small script to show you what i mean.

**Comment by knewron-technologies** [comment]
Hi,

Yes, a script example would help to understand in detail.

**Comment by ghost** [comment]
Ok. I create this. Give me a moment.

Can you give me a E-Mail address?

**Comment by knewron-technologies** [comment]
You can send it on 1btn@knewron.co.in
