### ISSUE TITLE
Can't configure 1btn over my1btn network

### ISSUE THREAD

**Issue by aidanreilly** [anandtamboli/1btn#6]
hi,

following these instructions: https://onedrive.live.com/embed?cid=1CCB31E5C4946157&resid=1CCB31E5C4946157!64753&authkey=ABqqwSvGLUfaemQ&em=2

i can't connect with MAC, Windows, IOS. I get the following error in termite. What is wrong?

![image](https://user-images.githubusercontent.com/5412997/67728166-1b74a600-f9e4-11e9-91f1-4bc43cbb8406.png)

Similiar to this issue: https://github.com/knewron-technologies/1btn/issues/3

Thanks.

**Comment by aidanreilly** [comment]
hi, just coming back to this. would be great to get this board up and running. any help much appreciated.

**Comment by rwatkins-BY** [comment]
Can anyone provide some information on how to configure a 1btn unit over my1btn network.   I have also followed these instructions : https://onedrive.live.com/embed?cid=1CCB31E5C4946157&resid=1CCB31E5C4946157!64753&authkey=ABqqwSvGLUfaemQ&em=2 
and it allows me to put in the password but when I go to a browser and put in 192.168.1.1, it never connects.  I am trying to use my android phone to make the connection at this point.

**Comment by knewron-technologies** [comment]
As you'll notice in error log "panic". A file seems to be missing. Can you compare it with the default files and see what's missing. Having that file on the device should help.

**Comment by aidanreilly** [comment]
I'm not a developer and I don't know how to get "files onto device" can you please elaborate. I think the default install procedure is broken.

**Comment by rwatkins-BY** [comment]
Ok.  I'm still not getting any where with these 1btn devices.  Can you tell me the exact cable that needs to be used between the laptop and the 1btn.  I have tried a micro-USB cable which fit the connection on the 1btn unit.  I have 1btn unit that the battery appears to have died on while testing and when using this micro-USB cable for charging it does not appear to be doing anything.  This cable works fine on my Justin Power stick so I know the cable is good but it might not be the correct cable for the 1btn unit.  
I also noticed when I connect initially to the 1btn unit via WiFi, you unit gets an IP address of 192.168.1.1 and within a short period of time it switches to 192.168.4.1.  I tried to connect to the unit via a IE, Google Chrome, & FireFox browsers using both IP addresses and I get the message the site can not be reached message regardless of which IP address I try. 
![image](https://user-images.githubusercontent.com/80426297/110823143-cdbaaf80-825f-11eb-9cf0-0467109e858f.png)
![image](https://user-images.githubusercontent.com/80426297/110822882-83d1c980-825f-11eb-8587-0a1f9c523b9c.png)
![image](https://user-images.githubusercontent.com/80426297/110822948-9b10b700-825f-11eb-948f-35d75bcc186f.png)

**Comment by rwatkins-BY** [comment]
I never received  a response to my question that I submitted last month.
